Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
        response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
23:05:01 Traceback (most recent call last):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1061, in perform_job
    rv = job.perform()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 821, in perform
    self._result = self._execute()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 844, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/jon/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 147, in execute_job
    method(**kwargs)
  File "/home/jon/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 1106, in create_contact
    contact.insert(
  File "/home/jon/frappe-bench/apps/frappe/frappe/model/document.py", line 250, in insert
    self._validate_links()
  File "/home/jon/frappe-bench/apps/frappe/frappe/model/document.py", line 899, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "/home/jon/frappe-bench/apps/frappe/frappe/__init__.py", line 522, in throw
    msgprint(
  File "/home/jon/frappe-bench/apps/frappe/frappe/__init__.py", line 490, in msgprint
    _raise_exception()
  File "/home/jon/frappe-bench/apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find User Id: jon_ronquillo@yahoo.com
Traceback (most recent call last):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1061, in perform_job
    rv = job.perform()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 821, in perform
    self._result = self._execute()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 844, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/jon/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 147, in execute_job
    method(**kwargs)
  File "/home/jon/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 1106, in create_contact
    contact.insert(
  File "/home/jon/frappe-bench/apps/frappe/frappe/model/document.py", line 250, in insert
    self._validate_links()
  File "/home/jon/frappe-bench/apps/frappe/frappe/model/document.py", line 899, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "/home/jon/frappe-bench/apps/frappe/frappe/__init__.py", line 522, in throw
    msgprint(
  File "/home/jon/frappe-bench/apps/frappe/frappe/__init__.py", line 490, in msgprint
    _raise_exception()
  File "/home/jon/frappe-bench/apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find User Id: jon_ronquillo@yahoo.com
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Traceback (most recent call last):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 198, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/_compat.py", line 72, in recv
Traceback (most recent call last):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 198, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/_compat.py", line 72, in recv
Traceback (most recent call last):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 198, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/_compat.py", line 72, in recv
    return sock.recv(*args, **kwargs)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return sock.recv(*args, **kwargs)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return sock.recv(*args, **kwargs)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jon/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jon/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jon/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
    main()
  File "/home/jon/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
Exception in thread     main()
  File "/home/jon/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
Exception in thread     main()
  File "/home/jon/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    return self.main(*args, **kwargs)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jon/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 189, in start_worker
Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    return self.main(*args, **kwargs)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jon/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 189, in start_worker
    start_worker(queue, quiet=quiet, rq_username=rq_username, rq_password=rq_password)
  File "/home/jon/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 205, in start_worker
    start_worker(queue, quiet=quiet, rq_username=rq_username, rq_password=rq_password)
  File "/home/jon/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 205, in start_worker
    return self.main(*args, **kwargs)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jon/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 189, in start_worker
    start_worker(queue, quiet=quiet, rq_username=rq_username, rq_password=rq_password)
  File "/home/jon/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 205, in start_worker
Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    Worker(queues, name=get_worker_name(queue_name)).work(logging_level=logging_level)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 637, in work
    Worker(queues, name=get_worker_name(queue_name)).work(logging_level=logging_level)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 637, in work
    self.register_death()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 337, in register_death
    p.execute()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 4019, in execute
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    self.register_death()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 337, in register_death
    p.execute()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 4019, in execute
    Worker(queues, name=get_worker_name(queue_name)).work(logging_level=logging_level)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 637, in work
    self.register_death()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 337, in register_death
    p.execute()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 4019, in execute
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    return execute(conn, stack, raise_on_error)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3894, in _execute_transaction
    return execute(conn, stack, raise_on_error)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3894, in _execute_transaction
    self.parse_response(connection, '_')
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 324, in read_response
    raw = self._buffer.readline()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 256, in readline
    self._read_from_socket()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 222, in _read_from_socket
    raise ConnectionError("Error while reading from socket: %s" %
redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')
    self.parse_response(connection, '_')
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 324, in read_response
    raw = self._buffer.readline()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 256, in readline
    self._read_from_socket()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 222, in _read_from_socket
    raise ConnectionError("Error while reading from socket: %s" %
redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')
    return execute(conn, stack, raise_on_error)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3894, in _execute_transaction
    self.parse_response(connection, '_')
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 324, in read_response
    raw = self._buffer.readline()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 256, in readline
    self._read_from_socket()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 222, in _read_from_socket
    raise ConnectionError("Error while reading from socket: %s" %
redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    if not block and not conn.can_read(timeout=timeout):
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/jon/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
